from __future__ import annotations

from datetime import datetime
from types import TracebackType
from typing import Protocol, Self

from app.domain.entities import (
    Action,
    AuditEvent,
    ComplaintAnalysis,
    Conversation,
    Customer,
    Incident,
    PolicyDocument,
    Transaction,
)
from app.domain.enums import ActionStatus, IncidentStatus


class CustomerRepository(Protocol):
    async def get(self, customer_id: str) -> Customer | None: ...
    async def list_all(self) -> list[Customer]: ...
    async def add(self, customer: Customer) -> None: ...


class TransactionRepository(Protocol):
    async def get(self, transaction_id: str) -> Transaction | None: ...
    async def latest_for_customer(self, customer_id: str) -> Transaction | None: ...
    async def list_for_customer(self, customer_id: str) -> list[Transaction]: ...
    async def add(self, transaction: Transaction) -> None: ...
    async def update(self, transaction: Transaction) -> None: ...


class PolicyRepository(Protocol):
    async def add(self, policy: PolicyDocument) -> None: ...
    async def list_all(self) -> list[PolicyDocument]: ...
    async def search(self, embedding: list[float], limit: int = 3) -> list[PolicyDocument]: ...


class ConversationRepository(Protocol):
    async def add(self, conversation: Conversation) -> None: ...
    async def list_recent(self, since: datetime) -> list[Conversation]: ...
    async def attach_incident(self, conversation_ids: list[str], incident_id: str) -> None: ...


class IncidentRepository(Protocol):
    async def get(self, incident_id: str) -> Incident | None: ...
    async def find_open_by_fingerprint(self, fingerprint: str) -> Incident | None: ...
    async def list_all(self) -> list[Incident]: ...
    async def add(self, incident: Incident) -> None: ...
    async def update(self, incident: Incident) -> None: ...


class ActionRepository(Protocol):
    async def get(self, action_id: str) -> Action | None: ...
    async def get_by_idempotency_key(self, key: str) -> Action | None: ...
    async def list_by_status(self, status: ActionStatus | None = None) -> list[Action]: ...
    async def add(self, action: Action) -> None: ...
    async def update(self, action: Action) -> None: ...


class AuditRepository(Protocol):
    async def add(self, event: AuditEvent) -> None: ...
    async def list_recent(self, limit: int = 100) -> list[AuditEvent]: ...


class MetricsRepository(Protocol):
    async def count_customers(self) -> int: ...
    async def count_conversations(self) -> int: ...
    async def count_incidents(self, statuses: set[IncidentStatus] | None = None) -> int: ...
    async def count_actions(self, status: ActionStatus | None = None) -> int: ...
    async def count_completed_actions(self) -> int: ...


class UnitOfWork(Protocol):
    customers: CustomerRepository
    transactions: TransactionRepository
    policies: PolicyRepository
    conversations: ConversationRepository
    incidents: IncidentRepository
    actions: ActionRepository
    audits: AuditRepository
    metrics: MetricsRepository

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class EmbeddingProvider(Protocol):
    async def embed(self, text: str) -> list[float]: ...


class ComplaintAnalyzer(Protocol):
    async def analyze(self, message: str) -> ComplaintAnalysis: ...


class AnswerGenerator(Protocol):
    async def generate(
        self,
        *,
        message: str,
        analysis: ComplaintAnalysis,
        policies: list[PolicyDocument],
        customer: Customer,
        transaction: Transaction | None,
        action_summary: str | None,
    ) -> str: ...


class ActionGateway(Protocol):
    async def issue_refund(self, transaction: Transaction, amount: float) -> str: ...
